
general:
  productiveBranch: 'main'
  verbose: true

steps:
  buildExecute:
    active: false   # 🚀 disables buildExecute step completely

  cpiUpload:
    host: 'https://dev-i77t4c8n.integrationsuite-trial.cfapps.us10-001.hana.ondemand.com'
    credentialsId: 'prod-user'   # Jenkins credential (username+password or API key)
    integrationFlowId: 'demo_Iflow'
    integrationFlowName: 'demo_Iflow'
    packageId: 'DEMO_PACKAGE'
