---
general:
  buildTool: "maven"
  chartPath: "gen/chart"
service:
  buildToolVersion: "MVNJ21"
stages:
  # 1. Checkout Stage
  - name: "Checkout Source"
    type: "git"
    repo: "https://github.com/shimeeh14/sap_cicd.git"
    branch: "main"
    credentialsId: "github"   # reference to stored Git credentials in CI/CD service

  # 5. Deploy to Integration Suite (Dev tenant)
  - name: "Deploy iFlow - Dev"
    type: "integrationSuiteDeploy"
    parameters:
      host: "https://<dev-tenant>.integration-suite.cfapps.<region>.hana.ondemand.com"
      username: "${{ secrets.CPI_USER }}"
      password: "${{ secrets.CPI_PASS }}"
      artifactId: "demo_Iflow"   # iFlow package name
      packageId: "DEMO_PACKAGE" # Package name in Integration Suite
      filePath: "demo_Iflow"

  
