
general:
  productiveBranch: 'main'
  verbose: true

steps:
  buildExecute:
    active: false     # disable build
  mtaBuild:
    active: false     # disable MTA build
  artifactPrepareVersion:
    active: false     # disable version step (requires mta.yaml)

  cpiUpload:
    host: 'https://dev-i77t4c8n.integrationsuite-trial.cfapps.us10-001.hana.ondemand.com'
    credentialsId: 'prod-user'   # Jenkins credential (username+password or API key)
    integrationFlowId: 'demo_Iflow'
    integrationFlowName: 'demo_Iflow'
    packageId: 'DEMO_PACKAGE'
