
general:
  buildTool: "none"
  verbose: true
  
stages:
  Init:
    git:
      repo: "https://github.com/shimeeh14/sap_cicd.git"
      branch: "main"
      credentialsId: "github"



  DeployDev:
    integrationSuiteDeploy:
      host: "https://dev-i77t4c8n.integrationsuite-trial.cfapps.us10-001.hana.ondemand.com"
      username: "${{ secrets.CPI_USER }}"
      password: "${{ secrets.CPI_PASS }}"
      artifactId: "demo_Iflow"
      packageId: "DEMO_PACKAGE"
      filePath: "demo_Iflow"


